# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Kingfisher Tutorial' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Kingfisher Tutorial
  pod 'Kingfisher', '~> 4.0'

end
